
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'data_labx4_potential_product_scoring_dbt'
version: '1.0.7'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'datalab'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  dev: 
    cz_europe_list: ('BE', 'FR')
    so_cz_europe_list: ('SO FRANCE', 'SO BELGIUM')
    start_year: 2023
  preprod: 
    cz_europe_list: ('BE', 'FR')
    so_cz_europe_list: ('SO FRANCE', 'SO BELGIUM')
    start_year: 2022
  prod:
    cz_europe_list: ('DE','SE','ES','CZ','IT','FR','HU','BE','PL','PT','RO','NL','CH','GB')
    so_cz_europe_list: ('SO FRANCE', 'SO GERMANY', 'SO SPAIN', 'SO ITALY', 'SO BELGIUM', 'SO UNITED KINGDOM', 'SO NETHERLANDS', 'SO PORTUGAL', 'SO POLAND', 'SO HUNGARY', 'SO ROMANIA', 'SO CZECH REPUBL', 'SO SWEDEN', 'SO SWITZERLAND')
    start_year: 2022
